# ------------------------------------------------------------------------------
#          ---        
#        / o o \    Snakemake workflow phylo-BEAST
#        V\ Y /V    Config file snakemake-phylo-BEAST
#    (\   / - \     
#     )) /    |     
#     ((/__) ||     Code by Ceci VA 
# ------------------------------------------------------------------------------

# use snakemake templates

run: # add phylogenetics as part of run definition
  analysis1:
    dataset: "dataset1"
    phylogenetics:
      tree_args: " -m GTR -nstop 50 -ninit 50 -bb 1000 -redo"
    phylodynamics:
      xml: "resources/beast_xml/example.xml"
      model_params:
        death_rate: 73.0

  analysis2:
    dataset: "dataset1"
    xml: "resources/beast_xml/example.xml"
    model_params:
      death_rate: 36.0

output:
  plot_dataset: true
  plot_tree: true
  check_ESS: true
  plot_parameters:
    - Re
    - ReAmongDemes
    - clockRate
# check ESS, if passed MCC tree and parameter plots (user defined parameters)
  # add config file for plotting output
  # check ess of chains already combined, user defined burnin or try different values automatically to maximize ess
  # use ugne's feast class to random initialize the parameters

lapis:
  seq_id: "strain" 
  database: "open" # gisaid or open

preprocessing:
  align: true
  mask: false

align:
  parameters:

mask:
  mask_from_beginning: 100
  mask_from_end: 200
  mask_sites: [21846, 21987, 22992, 23012, 23063, 23604, 24410]

ml_tree:
  tree_args: " -m GTR -nstop 50 -ninit 50 -bb 1000 -redo" #--date TAXNAME -o 'EPI_ISL_406798|China|2019-12-26' for time tree
  threads: 5

beast:
  length: 10000000
  time: 7200
  mem_mb: 4096
  threads: 10
  burnin: 10
  chains: 2
  action: "overwrite"
  java: "/cluster/home/ceciliav/lib/beast/jre/bin/java"
  jar: "resources/BDMM-Prime-rho.jar" 

  run:
    analysis1:
      dataset: "dataset1"
      xml: "resources/beast_xml/example.xml"
      model_params:
        death_rate: 73.0

    analysis2:
      dataset: "dataset1"
      xml: "resources/beast_xml/example.xml"
      model_params:
        death_rate: 36.0

