datasets:  

# Malawi

  Malawi_L1:
    subsampled:

  Malawi_L2:
    subsampled:

  Malawi_L3:
    subsampled:

  Malawi_L4:
    subsampled: 1

# Tanzania

  Tanzania_L1:
    subsampled:

  Tanzania_L2:
    subsampled:

  Tanzania_L3:
    subsampled: 1

  Tanzania_L4:
    subsampled:

# The Gambia

  TheGambia_L2:
    subsampled:

  TheGambia_L4:
    subsampled: 1

  TheGambia_L6:
    subsampled:

# Vietnam

  Vietnam_L1:
    subsampled:

  Vietnam_L2:
    subsampled: 1

  Vietnam_L4:
    subsampled:

